name: CDK Deployment
on: [workflow_dispatch]
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2      
        # Build your application here
        - run: echo 'Build and tests passed!'
  
        # Deploy stacks
        - name: cdk deploy all stacks
          uses: docker://kikemnzz/automate-cdk-github-action-kmzz:v1.0.0
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'us-west-2'
          with:
            cdk_action: 'deploy --verbose --require-approval never'
            

