name: CDK Deployment
on: [workflow_dispatch]
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: "us-west-2"
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
    
          - uses: actions/checkout@v3
            
          - name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
                python-version: "3.10"
          - name: Set up Node
            uses: actions/setup-node@v3
            with:
                node-version: "16"
          
          - name: Install dependencies
            run: |
                pip install --upgrade pip pre-commit poetry
                npm install -g aws-cdk
                pip install -r requirements.txt
        
          - name: cdk bootstrap
            uses: tj-actions/aws-cdk@v4
            with:
              cdk_subcommand: "bootstrap"
              

    
          - name: cdk synth
            uses: tj-actions/aws-cdk@v4
            with:
              cdk_subcommand: "synth"

 