name: CDK Deployment
on: [workflow_dispatch]
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: cdk synth
          uses: arnaskro/aws-cdk-v2-github-actions@v2.2.1
          with:
            cdk_subcommand: 'synth'
          
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'us-west-2'

